version: "2"
services:
  app:
    container_name: blog
    image: blog
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - redis
      - postgres
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blog
    ports:
      - 5432:5432